name = "madarch"
description = "Ray-marching engine in Ada and GLSL"
version = "0.0.1"

authors = ["Romain Beguet"]
maintainers = ["Romain Beguet <beguet@adacore.com>"]
maintainers-logins = ["Roldak"]
[[depends-on]]  # Added by alr
gnatcoll = "^22.0.0"  # Added by alr
[[depends-on]]  # Added by alr
openglada = "~0.9.0"  # Added by alr
[[depends-on]]  # Added by alr
openglada_glfw = "~0.9.0"  # Added by alr
